[features]
seeds = false
skip-lint = false
[programs.localnet]
dtt = "F18piyUM9ccShzRZMG8y6TmQT8YttYB5mPW6WY2LyMkH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marche/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
