[features]
seeds = false
skip-lint = false
[programs.localnet]
ddt = "4P1gf2p6cji6e23uw4FpKLqXx6ecg12rfBXnk8Mrrdyg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marche/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
