[features]
seeds = false
[programs.localnet]
coin_flip = "GWZnKS5wKpdqcgCgjQn9enk4YaRRAnLsFvVBLFYeXYP9"
[programs.devnet]
coin_flip = "GWZnKS5wKpdqcgCgjQn9enk4YaRRAnLsFvVBLFYeXYP9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/natalieyeo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/coin-flip.ts"
